---@class FittenCode.UV.Process
---@field _callbacks table<string, function[]>
---@field aborted boolean
---@field on function
---@field _emit function
---@field abort function
---@field run function

---@class FittenCode.UV.FS
---@field close function
---@field open function
---@field read fun(fd, size, offset) : FittenCode.Concurrency.Promise
---@field write function
---@field unlink function
---@field mkdir function
---@field mkdtemp function
---@field mkstemp function
---@field rmdir function
---@field scandir function
---@field stat function
---@field fstat function
---@field lstat function
---@field rename function
---@field fsync function
---@field fdatasync function
---@field ftruncate function
---@field sendfile function
---@field access function
---@field chmod function
---@field fchmod function
---@field utime function
---@field futime function
---@field lutime function
---@field link function
---@field symlink function
---@field readlink function
---@field realpath function
---@field chown function
---@field fchown function
---@field lchown function
---@field copyfile function
---@field opendir function
---@field readdir function
---@field closedir function
---@field statfs function
