---@class FittenCode.KeyStorage
---@field store function
---@field delete function
---@field get function
---@field purge_storage function

---@class FittenCode.PlainStorage
---@field _storage_dir string
---@field _data_file string

-- {
--     "access_token": "..-",
--     "refresh_token": "..--",
--     "user_info": {
--         "user_id": "659dec9189d3ad42d84f9619",
--         "username": "luozhiya",
--         "phone": "15273289380",
--         "nickname": "",
--         "email": "",
--         "token": "..--",
--         "registration_time": "2024-02-18T14:38:48.749000",
--         "user_type": "普通用户",
--         "account_status": "正常",
--         "register_username": "",
--         "wechat_info": null,
--         "firebase_info": null,
--         "client_token": "",
--         "client_time": 0,
--         "company": ""
--     }
-- }

---@class FittenCode.PlatformInfo
---@field ide string
---@field ide_name string
---@field ide_version string
---@field os string
---@field os_version string
---@field extension_version string

---@class FittenCode.Client.RequestOptions : FittenCode.AsyncIOCallbacks
---@field body? string
---@field timeout? number
---@field variables? table<string, any>
